/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sJIlQMI2NjJ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function CataloguePage() {
  return (
    <main className="w-full max-w-6xl mx-auto px-4 md:px-6 py-12 md:py-24">
      <div className="space-y-8">
        <div className="space-y-4">
          <h1 className="text-4xl font-bold">Web3 Course Catalog</h1>
          <p className="text-gray-500 dark:text-gray-400 text-lg">
            Dive into the world of blockchain, dApps, smart contracts, and
            cryptocurrencies with our interactive learning resources.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Blockchain Fundamentals</CardTitle>
              <CardDescription>
                Learn the core concepts of blockchain technology, including
                decentralization, consensus mechanisms, and cryptography.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold">Course Outline</h3>
                  <ul className="space-y-2 mt-2">
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Introduction to Blockchain
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Decentralization and Consensus Mechanisms
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Cryptography and Security
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Blockchain Applications and Use Cases
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-semibold">Learning Resources</h3>
                  <ul className="space-y-2 mt-2">
                    <li>
                      <CirclePlayIcon className="w-5 h-5 text-blue-500 inline-block mr-2" />
                      Video Lectures
                    </li>
                    <li>
                      <PencilIcon className="w-5 h-5 text-orange-500 inline-block mr-2" />
                      Interactive Quizzes
                    </li>
                    <li>
                      <CodeIcon className="w-5 h-5 text-purple-500 inline-block mr-2" />
                      Coding Challenges
                    </li>
                    <li>
                      <TrophyIcon className="w-5 h-5 text-yellow-500 inline-block mr-2" />
                      Gamified Learning
                    </li>
                  </ul>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button>Enroll Now</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Decentralized Applications (dApps)</CardTitle>
              <CardDescription>
                Learn how to build decentralized applications (dApps) on top of
                blockchain networks.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold">Course Outline</h3>
                  <ul className="space-y-2 mt-2">
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Introduction to dApps
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Ethereum and Smart Contracts
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Building and Deploying dApps
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      dApp Architectures and Design Patterns
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-semibold">Learning Resources</h3>
                  <ul className="space-y-2 mt-2">
                    <li>
                      <CirclePlayIcon className="w-5 h-5 text-blue-500 inline-block mr-2" />
                      Video Tutorials
                    </li>
                    <li>
                      <PencilIcon className="w-5 h-5 text-orange-500 inline-block mr-2" />
                      Interactive Coding Exercises
                    </li>
                    <li>
                      <CodeIcon className="w-5 h-5 text-purple-500 inline-block mr-2" />
                      Project-based Learning
                    </li>
                    <li>
                      <TrophyIcon className="w-5 h-5 text-yellow-500 inline-block mr-2" />
                      Achievements and Badges
                    </li>
                  </ul>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button>Enroll Now</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Smart Contracts and Solidity</CardTitle>
              <CardDescription>
                Dive into the world of smart contracts and learn how to write,
                deploy, and interact with them using Solidity.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold">Course Outline</h3>
                  <ul className="space-y-2 mt-2">
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Introduction to Smart Contracts
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Solidity Programming Language
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Deploying and Interacting with Smart Contracts
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Advanced Smart Contract Patterns and Security
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-semibold">Learning Resources</h3>
                  <ul className="space-y-2 mt-2">
                    <li>
                      <CirclePlayIcon className="w-5 h-5 text-blue-500 inline-block mr-2" />
                      Video Walkthroughs
                    </li>
                    <li>
                      <PencilIcon className="w-5 h-5 text-orange-500 inline-block mr-2" />
                      Hands-on Coding Exercises
                    </li>
                    <li>
                      <CodeIcon className="w-5 h-5 text-purple-500 inline-block mr-2" />
                      Project-based Assignments
                    </li>
                    <li>
                      <TrophyIcon className="w-5 h-5 text-yellow-500 inline-block mr-2" />
                      Leaderboards and Achievements
                    </li>
                  </ul>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button>Enroll Now</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Cryptocurrencies and DeFi</CardTitle>
              <CardDescription>
                Explore the world of cryptocurrencies, decentralized finance
                (DeFi), and the various protocols and applications in this
                space.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold">Course Outline</h3>
                  <ul className="space-y-2 mt-2">
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Introduction to Cryptocurrencies
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Decentralized Finance (DeFi) Protocols
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Trading and Investment Strategies
                    </li>
                    <li>
                      <CircleCheckIcon className="w-5 h-5 text-green-500 inline-block mr-2" />
                      Regulatory Landscape and Compliance
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-semibold">Learning Resources</h3>
                  <ul className="space-y-2 mt-2">
                    <li>
                      <CirclePlayIcon className="w-5 h-5 text-blue-500 inline-block mr-2" />
                      Interactive Simulations
                    </li>
                    <li>
                      <PencilIcon className="w-5 h-5 text-orange-500 inline-block mr-2" />
                      Market Analysis Exercises
                    </li>
                    <li>
                      <CodeIcon className="w-5 h-5 text-purple-500 inline-block mr-2" />
                      DeFi Protocol Integrations
                    </li>
                    <li>
                      <TrophyIcon className="w-5 h-5 text-yellow-500 inline-block mr-2" />
                      Trading Competitions
                    </li>
                  </ul>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button>Enroll Now</Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </main>
  );
}

function CircleCheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  );
}

function CirclePlayIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polygon points="10 8 16 12 10 16 10 8" />
    </svg>
  );
}

function CodeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}

function PencilIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  );
}

function TrophyIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>
  );
}
